applogin/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'applogin'

urlpatterns = [
	path('', views.landingpage, name='landingpage'),
    path('login/', views.loginpage, name='loginpage'),
    path('menu/', views.menupage, name='menupage'),
    path('logout/',views.logoutpage, name='logoutpage'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applogin.urls')),
]

applogin/models.py
from django.db import models

# Create your models here.

applogin/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def loginpage(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('applogin:menupage')
	else:
		form = AuthenticationForm()
	return render(request, 'login.html', {'form':form})

def landingpage(request):
	return render(request, 'landing.html')

def menupage(request):
	if request.user.is_authenticated:
		return render(request,'menu.html')
	else:
		return redirect('applogin:loginpage')

def logoutpage(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			logout(request)
	return redirect('applogin:landingpage')

applogin/templates/landing.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>website login gue</title>
</head>
<style>
	body{
		background-color: #c4c4c4;
		text-align: center;
		margin-top: 200px;
	}

</style>

<body>
	<h1>Halaman Utama</h1>
	{% if not user.is_authenticated %}
	<a href="{%url 'applogin:loginpage' %}">Pencet Disini</a>
	{% endif %}
</body>

applogin/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>website login gue</title>
</head>
<style>
	body{
		background-color: #c4c4c4;
		text-align: center;
		margin-top: 200px;
	}

</style>

<body>
	 <h1>Login</h1>
	 <form class="site-form" action="{%url 'applogin:loginpage' %}" method="post">
	 	{% csrf_token %}
	 	<div id="flexbox-container">
	 	{{form.as_p}}
	 	</div>
	 	<input type="submit" value="Login">
	 </form>
</body>

applogin/templates/menu.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>website login gue</title>
</head>
<style>
	body{
		background-color: #c4c4c4;
		text-align: center;
		margin-top: 200px;
	}

</style>

<body>
	<h1>Selamat! Anda berhasil login</h1>
	{% if user.is_authenticated %}
	<h3>Welcome {{ user.username }}!</h3>
	<form class="logout-link" action="{%url 'applogin:logoutpage' %}" method="post">
		{% csrf_token %}
		<button type="submit">Logout</button>
	</form>
	{% endif %}
	
</body>